name: Octopus Install
on: [push, pull_request]

jobs:
  build:
    name: Run Script
    runs-on: windows
    steps:
      - uses: actions/checkout@v1
      - name: Script
        run: ./script.ps1
        shell: pwsh
        
