name: install_tf_win

description: installs Terraform/TerraGrunt for Windows

runs:
  using: "composite"
  steps:
      #- run: '& $env:tyler5136/tcoctopusagentrepo/install-tf-win/install-tf-win.ps1'
      - run: winver
      shell: powershell
